server:
    port: 8081
spring:
    application:
        name: products
    datasource:
        url: jdbc:mysql://localhost:3306/products?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: root
    jpa:
        show-sql: true
logging:
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){cyan} %highlight(%-5level) %msg%n"
